{
    'name': "Field Service App",
    'version': "1.23.07",
    'category': 'Sales/CRM',
    'author': "Mongrov",
    'depends': ['base', 'hr', 'calendar', 'hr_attendance','web'],
    "external_dependencies": {"python": [], "bin": []},
    'installable': True,
    'application': True,
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'view/web_views.xml',
        'view/assets.xml',
        'data/data.xml',
        # 'data/mail_data.xml',
        'view/eng_schedule_edit.xml',
        'view/call_report.xml',
        'view/engineerinfo.xml',
        'view/labour_info_view.xml',
        'view/material_activities.xml',
        'view/engineer_calendar.xml',
        # 'view/calendar_view.xml',
        'view/resconfig.xml',
        'view/engineerapproval.xml',
        # 'view/engg_occupancy.xml',
        'view/metabase.xml',
        'view/metabase_rs_tat.xml',
        'view/blog.xml',
        'view/metabase_repeatcall.xml',
        'view/metabase_firsttime_fix.xml',
        'view/change_request.xml',
        'view/material_order.xml',
        # 'view/customerinfo.xml',
        'view/support_view.xml',
        'view/hrattendance.xml',
        'view/notification.xml',
        'view/facetime_report.xml',
        'view/workbenchinfo.xml',
        'view/lov_master.xml',
        # 'view/part_code.xml',
        # 'view/part_order.xml',
        'view/timesheet_view.xml',
        # 'view/product.xml',
        'view/sla.xml',
        'view/call_view_admin.xml',
        'view/cms_managers.xml',
        'view/product_model_and_rating.xml',
        'view/cms_problem_setup.xml',
        # 'view/cms_info_view.xml',
# 'view/cms_report.xml',
'view/cms_call_close.xml',
'view/menu.xml',

         ],
    'qweb': ['static/src/xml/*.xml']

    # 'pre_init_hook': 'pre_init_hook_login_check',
    # 'post_init_hook': 'post_init_hook_login_convert',
}