SELECT "public"."cms_info_model"."zone" AS "zone", count(distinct "public"."cms_info_model"."call_no") AS "count", sum("Question 64"."facetime") AS "sum", count(distinct "public"."cms_info_model"."engineerId") AS "count_2"
FROM "public"."cms_info_model"
LEFT JOIN (SELECT "source"."id" AS "id", "source"."call_id" AS "call_id", "source"."punch_category" AS "punch_category", "source"."punch_type" AS "punch_type", "source"."start_time" AS "start_time", "source"."end_time" AS "end_time", "source"."facetime" AS "facetime"
FROM (SELECT "public"."call_timesheet_info"."id" AS "id", "public"."call_timesheet_info"."call_id" AS "call_id", "public"."call_timesheet_info"."punch_category" AS "punch_category", "public"."call_timesheet_info"."punch_type" AS "punch_type", "public"."call_timesheet_info"."start_time" AS "start_time", "public"."call_timesheet_info"."end_time" AS "end_time", "public"."call_timesheet_info"."start_notes" AS "start_notes", "public"."call_timesheet_info"."close_notes" AS "close_notes", extract (epoch from("public"."call_timesheet_info"."end_time" - "public"."call_timesheet_info"."start_time"))/3600 AS "facetime" FROM "public"."call_timesheet_info") "source"
WHERE "source"."punch_category" = 'Equipmentfacetime'
LIMIT 1048575) "Question 64" ON "public"."cms_info_model"."id" = "Question 64"."call_id" LEFT JOIN (SELECT "public"."hr_employee"."id" AS "id", "public"."hr_employee"."parent_id" AS "parent_id", "public"."hr_employee"."name" AS "Engineer", "Hr Employee - Parent"."name" AS "Manager", "Question 65"."employee_id" AS "Question 65__employee_id", "Question 65"."check_out" AS "Check out Date", "Question 65"."sum" AS "Total Hrs"
FROM "public"."hr_employee"
LEFT JOIN "public"."hr_employee" "Hr Employee - Parent" ON "public"."hr_employee"."parent_id" = "Hr Employee - Parent"."id" LEFT JOIN (SELECT "public"."hr_attendance"."employee_id" AS "employee_id", CAST("public"."hr_attendance"."check_out" AS date) AS "check_out", count(*) AS "count", sum("public"."hr_attendance"."worked_hours") AS "sum" FROM "public"."hr_attendance"
GROUP BY "public"."hr_attendance"."employee_id", CAST("public"."hr_attendance"."check_out" AS date)) "Question 65" ON "public"."hr_employee"."id" = "Question 65"."employee_id"
ORDER BY "public"."hr_employee"."name" ASC
LIMIT 1048575) "Question 72" ON "public"."cms_info_model"."engineerId" = "Question 72"."id" WHERE ("public"."cms_info_model"."call_status" = 'Completed'
    OR "public"."cms_info_model"."call_status" = 'Closed') GROUP BY "public"."cms_info_model"."zone" ORDER BY "public"."cms_info_model"."zone" ASC