SELECT "source"."engineerId" AS "engineerId", count(distinct "source"."call_no") AS "count", sum("source"."facetime") AS "sum", avg("source"."sum") AS "avg", sum("source"."Percentage") AS "sum_2"
FROM (SELECT "public"."cms_info_model"."call_no" AS "call_no", "Question 64"."facetime" AS "facetime", "Question 65"."sum" AS "sum", (CAST("Question 64"."facetime" AS float) / CASE WHEN "Question 65"."sum" = 0 THEN NULL ELSE "Question 65"."sum" END) AS "Percentage", "public"."cms_info_model"."call_status" AS "call_status", "public"."cms_info_model"."engineerId" AS "engineerId" FROM "public"."cms_info_model"
LEFT JOIN (SELECT "source"."id" AS "id", "source"."call_id" AS "call_id", "source"."punch_category" AS "punch_category", "source"."punch_type" AS "punch_type", "source"."start_time" AS "start_time", "source"."end_time" AS "end_time", "source"."facetime" AS "facetime"
FROM (SELECT "public"."call_timesheet_info"."id" AS "id", "public"."call_timesheet_info"."call_id" AS "call_id", "public"."call_timesheet_info"."punch_category" AS "punch_category", "public"."call_timesheet_info"."punch_type" AS "punch_type", "public"."call_timesheet_info"."start_time" AS "start_time", "public"."call_timesheet_info"."end_time" AS "end_time", "public"."call_timesheet_info"."start_notes" AS "start_notes", "public"."call_timesheet_info"."close_notes" AS "close_notes", extract (epoch from("public"."call_timesheet_info"."end_time" - "public"."call_timesheet_info"."start_time"))/3600 AS "facetime" FROM "public"."call_timesheet_info") "source"
WHERE "source"."punch_category" = 'Equipmentfacetime'
LIMIT 1048575) "Question 64" ON "public"."cms_info_model"."id" = "Question 64"."call_id" LEFT JOIN (SELECT "public"."hr_attendance"."employee_id" AS "employee_id", CAST("public"."hr_attendance"."check_out" AS date) AS "check_out", count(*) AS "count", sum("public"."hr_attendance"."worked_hours") AS "sum" FROM "public"."hr_attendance"
GROUP BY "public"."hr_attendance"."employee_id", CAST("public"."hr_attendance"."check_out" AS date)) "Question 65" ON "public"."cms_info_model"."engineerId" = "Question 65"."employee_id") "source" WHERE (("source"."call_status" = 'Completed'
    OR "source"."call_status" = 'Closed')
   AND "source"."engineerId" IS NOT NULL) GROUP BY "source"."engineerId"
ORDER BY "source"."engineerId" ASC